### ISSUE TITLE
intel_gpu_top GAM is out of range,so what can I do ? what is GAM?

### ISSUE THREAD

**Issue by waiter89** [01org/libva#104]
render busy:  48%: █████████▋                             render space: 49/16384

                          task  percent busy
                           GAM:  99%: ███████████████████▉    vert fetch: 0 (0/sec)
                            CS:  49%: █████████▉              prim fetch: 0 (0/sec)
                           SDE:   2%: ▌                    VS invocations: 0 (0/sec)
                            RS:   0%:                      GS invocations: 0 (0/sec)
                           TSG:   0%:                           GS prims: 0 (0/sec)
                           VFE:   0%:                      CL invocations: 0 (0/sec)
                          GAFM:   0%:                           CL prims: 0 (0/sec)
                           SOL:   0%:                      PS invocations: 0 (0/sec)
                            VS:   0%:                      PS depth pass: 0 (0/sec)
                            SF:   0%:                      
                            GS:   0%:                      
                            CL:   0%:                      
                            VF:   0%:                      
                           SVG:   0%:

**Comment by xhaihao** [comment]
Here is for VA-API and related issue/topic, not for intel_gpu_top,  could you please file your issue to the right place?  As for GAM, please download the PRM for Intel GPU from https://01.org/linuxgraphics/documentation/hardware-specification-prms
