### ISSUE TITLE
wayland: thread safety and leaked proxies

### ISSUE THREAD

**Issue by seanvk** [01org/libva#11]
migrated from Bugzilla [#90200](https://bugs.freedesktop.org/show_bug.cgi?id=90200)
status NEEDINFO severity *normal* in component *core* for *---*
Reported in version *unspecified* on platform *Other*
Assigned to: haihao

Original attachment names and IDs:
- _[0001-wayland-Use-a-private-queue-and-free-registry-proxy.patch](https://bugs.freedesktop.org//attachment.cgi?id=115381)_ (ID 115381)
- _[0001-wayland-Use-private-queue-and-free-proxy.patch](https://bugs.freedesktop.org//attachment.cgi?id=115382)_ (ID 115382)

On 2015-04-27 18:21:27 +0000, Olivier CrÃªte wrote:

> Created attachment 115381
> libva: wayland: Use a private queue and free registry proxy
> 
> both libva and the intel driver's wayland integration use the global queue. This is not thread safe and may be problematic for some applications. Also, it doesn't clear the proxies and queue correctly before unloading the libEGL.so, which leads to segfaults as libwayland-client tries to access the static wl_interface in the bit that has been unloaded!

On 2015-04-27 18:21:56 +0000, Olivier CrÃªte wrote:

> Created attachment 115382
> intel-driver: Basically the same patch for the driver

On 2015-04-30 01:03:44 +0000, haihao wrote:

> The old version of wayland-client.h doesn't have wl_display_roundtrip_queue. Could you update the dependency on wayland in configure.ac too ?

On 2015-11-24 04:43:38 +0000, haihao wrote:

> Could you update your patch to check wayland version? otherwise your patch might break driver building.

On 2016-08-31 04:03:06 +0000, Gautham Kantharaju wrote:

> Using vaapisink for video playback, trying to stop/start the video playback or switch video files.
> 
> SIGSEGV is caught in libwayland-client. Pulled in the patches w.r.t libva and libva-intel-driver. Still the issue exists.
> 
> Can you let me know, if anything needs to be changed the vaapi gstreamer plugin also in order to resolve the issue?

On 2016-09-05 01:50:46 +0000, haihao wrote:

> Someone also reported crash issue when using wayland, the issue disappears after upgrading wanyland-drm in the driver. Could you have a try with the following patches:
> 
> libva:
> https://lists.freedesktop.org/archives/libva/2016-September/004356.html
> https://lists.freedesktop.org/archives/libva/2016-September/004357.html
> 
> libva-intel-driver:
> https://lists.freedesktop.org/archives/libva/2016-September/004361.html
> https://lists.freedesktop.org/archives/libva/2016-September/004362.html

**Comment by pkerling** [comment]
Hi,
what's preventing the inclusion of the two patches? I'm implementing Wayland support in Kodi, and this bug reliably crashes the entire application. I can confirm that the first patch (for libva) fixes the issue. We don't use the `wl_buffer` stuff in libva so I can't try the intel-vaapi-driver patch, but I'm quite sure that it would also crash without the patch.

**Comment by xhaihao** [comment]
@pkerling User still experienced the issue, please refer to the comments from Gautham Kantharaju

**Comment by pkerling** [comment]
@xhaihao What makes you think that what the user experienced is related to this bug given the very small amount of information? The patches here improve the situation since what the code does at the moment is plainly broken and there is no chance that it will reliably work. If there are still issues then, they need to be analyzed separately. There also has been no response or additional information on the issue experienced by Gautham Kantharaju for almost a year.

On another note, the patches are still not completely right. They use `wl_proxy_set_queue` on the `wl_display` without first using `wl_proxy_create_wrapper`, which still allows for a tiny window in which a race could occur (see `wl_proxy_create_wrapper` documentation). I'm willing to correct that though if you would consider it for merging then.

**Comment by xhaihao** [comment]
@pkerling agree with you that the issue Gautham experienced might be another issue.  We didn't get response from Olivier or Gautham, hence we don't merge the patches. It would be great if you can update the patches.

**Comment by pkerling** [comment]
@xhaihao please take a look at the PRs
