### ISSUE TITLE
VP9 on Ubuntu 17.10 beta2

### ISSUE THREAD

**Issue by newcgen** [01org/libva#129]
Hello!

I see artifacts during video playback VP9 format.
iris plus 640, libva 1.8.3.

**Comment by xhaihao** [comment]
We have fixed this issue on master and the next release will include the corresponding patch.  Please refer to https://github.com/01org/intel-vaapi-driver/issues/262 for detail.

BTW please file the issue on https://github.com/01org/intel-vaapi-driver/issues for driver related issue.
