### ISSUE TITLE
Tags for releases > 1.7.3 are missing

### ISSUE THREAD

**Issue by yellowdoge** [01org/libva#136]
The [NEWS file](https://github.com/01org/libva/blob/master/NEWS) refers to releases for which there are !no tags (original link: https://imgur.com/a/79zKD). Please make them.

![tags](https://i.imgur.com/rspnZTq.png)

**Comment by yellowdoge** [comment]
From the command line I can see the numeric version tags > 1.7.3:
```
$ git tag
04032009
04082009
04132009
04142009
04212009_Alpha1.1
04212009_Alpha1.1-DRI2
04282009_ww18
04302009_Alpha1.2
05082009_Alpha1.3
05142009_Alpha1.4
05212009_Alpha1.5
05282009_Alpha2.1
1.0.7
1.4.0.pre1
1.4.1.pre1
1.8.0
1.8.0.pre1
1.8.0.pre2
1.8.0.pre3
1.8.1
1.8.1.pre1
1.8.2
1.8.2.pre1
1.8.3
1.8.3.pre1
2.0.0
2.0.0.pre1
2.0.0.pre2
2.0.0.pre3
20090306
[..]
```
But not from the Github tag browser. Could we add the named tags please? Thanks!

**Comment by chivakker** [comment]
Hi Miguel,

I can see all releases on this link
https://github.com/01org/intel-vaapi-driver/releases

The NEWS file has all the releases as well.

-- 
Daniel.

**Comment by yellowdoge** [comment]
@chivakker, correct, the releases have labels and tags, like I said in https://github.com/01org/libva/issues/136#issuecomment-343213290, but there's no easy way to access a snapshot of those releases _from the GitHub interface_, because the tag lacks some leading text. Hence this issue :-)

**Comment by chivakker** [comment]
@yellowdoge now I get you, yeah tags are available but they don't show up on github only.  Isn't that more like a github issue?  We could double tag (if there's a hard requirement from github) but number only tags should be kept as it is used by gentoo building system (also ChromeOS)

**Comment by yellowdoge** [comment]
@chivakker, yeah, double tagging would be grand, thanks.

**Comment by chivakker** [comment]
@xhaihao: could you do a double tagging to work around github's web interface?  In general terms it should be a no-op everywhere else.

**Comment by xhaihao** [comment]
@yellowdoge I pushed another tag 'libva-1.8.0' for 1.8.0 release, could you give a try? If it works, I will do a double tagging for other releases.

**Comment by chivakker** [comment]
@xhaihao yes it is working.

**Comment by xhaihao** [comment]
libva-1.8.1/libva-1.8.2/libva-1.8.3/libva-2.0.0 are added as well. BTW the github's web interface works well with intel-vaapi-driver, it seems only libva has this issue.

**Comment by yellowdoge** [comment]
Working now for me too, thanks!
