### ISSUE TITLE
libva trace fails in more than 64 VAContexts

### ISSUE THREAD

**Issue by yakuizhao** [01org/libva#142]
Currently the Libva trace uses the result of context_id & 63 as hash_key to log the corresponding trace_context info.
Unfortunately this will fail if the middleware tries to create more than 64 context. 
For example: Libva trace log complains the below error info for the context 0x04000040
>Can't get trace context for ctx 0x04000040.

At the same time if the backend driver uses the another mechanism to allocate the corresponding ContextID, it will also fail in libva trace. 
     For example:  The result of Decode ContextID & 0x3F is the same as that of encode ContextID & 0x3F although the different ContextId is  used for decode/encode.

**Comment by yakuizhao** [comment]
Any progress?

**Comment by pengche1** [comment]
It should be two issues. 1, the maximum context number is 64, it will be easy to extend this size. but it will consume more memory. so is it the common case to use so much contexts? 2, ContextID & 0x3F issue. It can find another free entry for the second context id with the same hash_key. I will try to fix it
