### ISSUE TITLE
About encoding 10 or 12 bits video

### ISSUE THREAD

**Issue by lm124757** [01org/libva#143]
Hello, I'm new to libva. I want to know if libva support encoding 10 or 12 bits video data. In other words, does it support h264's high10 profile or h265's main10/main12 profile? I'm using ubuntu on a computer with 
intel Iris Graphics 540 gpu. Thanks if somebody knows.

**Comment by xhaihao** [comment]
1. libva doesn't support h264 high10 profile
2. libva supports h265 main10 profile, it doesn't support h265 main12 profile
3. You may run 'vainfo' to check the capabilities of your GPU, vainfo can print out the supported profile/entrypoint pairs

**Comment by lm124757** [comment]
Thanks.
