### ISSUE TITLE
Need to update yocto upstream

### ISSUE THREAD

**Issue by seanvk** [01org/libva#17]
Yocto recipes for libva are still pointing to FDO.  Maybe we could file a bug with them or submit an updated recipe.

**Comment by seanvk** [comment]
https://bugzilla.yoctoproject.org/show_bug.cgi?id=10999

**Comment by seanvk** [comment]
Saul Wold changed bug 10999 
What	Removed	Added
Status	IN PROGRESS IMPLEMENTATION	RESOLVED
Resolution	---	FIXED
Comment # 4 on bug 10999 from Saul Wold
Merged the libva change to oe-core:

http://git.yoctoproject.org/cgit/cgit.cgi/poky/commit/?id=73d1c2713725602549fff99434be24fe593d80bb

and into meta-intel here for libva-intel-driver:

http://git.yoctoproject.org/cgit/cgit.cgi/meta-intel/commit/?id=0c2da994195b4db36db80258d09d0e5faed22136

Both now use the github repo directly and when updates occur we will need to
update the SRCREV SHAs

**Comment by xhaihao** [comment]
Closed per Sean's last comment
