### ISSUE TITLE
va_getDriverName() fails if vaapi already in use

### ISSUE THREAD

**Issue by tmm1** [01org/libva#20]
This appears to be a regression in 4dc07b2298840bb75de2f7e78a5abe63adaff236

Previously I could use two parallel processes both using vaapi to do hardware h264 encoding. After that commit, the second process fails to initialize with the following error:

```
libva info: VA-API version 0.40.0
libva info: va_getDriverName() returns 1
libva error: va_getDriverName() failed with operation failed,driver_name=i965
```

cc @evelikov @seanvk

**Comment by tmm1** [comment]
FWIW, I'm seeing this behavior on a linux 3.12.6 machine with a Celeron J1900, when using `/dev/dri/card0` (no render node available).

**Comment by tmm1** [comment]
I confirmed that things are working as expected again after reverting 4dc07b2

**Comment by xhaihao** [comment]
@tmm1 

You are using vaapi as root user, right ? Please use render node if you want to run 2+ vaapi applications at the same time.  See https://lists.freedesktop.org/archives/libva/2016-November/004780.html for detail.

**Comment by seanvk** [comment]
Agree with @xhaihao render node is what you should be using to share it.

**Comment by tmm1** [comment]
On my system no render node is available, as noted in my second comment. I am using a commercial QNAP NAS device and the OS/kernel is provided by the vendor. AFAIK the 3.12 series contains the render split patches but none of the various QNAP models I have checked provide the dev device.

**Comment by seanvk** [comment]
Who is the owner of the processes performing the encoding?  Are both running as root?

**Comment by tmm1** [comment]
Yes, "apps" installed onto the NAS run as uid 0.

Thanks for the link to the mailing list thread.

**Comment by seanvk** [comment]
So that's the problem.  You should have a service user with access control for running the apps.  Running the apps as uid 0 is not the way to go.

**Comment by tmm1** [comment]
I understand that running as root is not recommended, but that's the way the vendor has setup this device.

It seems to me this is a regression as it was working without issue before, but I understand that this is considered a WONTFIX.
