### ISSUE TITLE
[feature request] disable informative messages

### ISSUE THREAD

**Issue by effemmeffe** [01org/libva#21]
In my .xsession-errors I found this messages:
```
libva info: VA-API version 0.39.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_39
libva info: va_openDriver() returns 0
```
I'd like to have the ability to disable those messages.
This will avoid to make the file grow in machines that runs kodi and are not rebooted often.

**Comment by effemmeffe** [comment]
I'm pretty newbie, how do I upgrade my vesion on ubuntu? And how do I disable this?

**Comment by xhaihao** [comment]
Please follow the steps below to build your libva './autogen.sh --enable-va-messaging=no' or './configure --enable-va-messaging=no' if configure has been updated then build and install libva.

**Comment by xhaihao** [comment]
Please follow the steps below to build your libva

**Comment by xhaihao** [comment]
First you should clone or download the source code from https://github.com/01org/libva, otherwise you have to wait for the new version of libva in Ubuntu.  

Then please follow the steps below to build and install the new libva:
1. 
$> ./autogen.sh --enable-va-messaging=no ... 
... is other options, e.g. --prefix to change the install path prefix. If configure has been updated, you can run configure directly:
$> ./configure --enable-va-messaging=no ...
2. 
$> make
3.
$> sudo make install

**Comment by effemmeffe** [comment]
Thank you.
How do I follow the path for a new version in ubuntu?
Right now ubuntu 16.04 provides libva package 1.7.0-1, how do I check that this change is included in the ubuntu package?

**Comment by xhaihao** [comment]
I don't know when Ubuntu will integrate the latest libva. For us, we usually build an official release per quarter.

**Comment by uartie** [comment]
The proposed patch (#22) only allows "messaging" to be disabled at compile time.  And it is enabled by default.  If distros don't explicitly disable it during compilation, then users are back at square one.  On the flip-side, if distros do disable it then there is no way to turn it back on when users have issues to report/debug.  Wouldn't it be better to add a runtime check, at initialization stage or something, so users can disable/enable it per application run (perhaps by setting an environment variable)?

**Comment by seanvk** [comment]
Patch is already merged.  I'd prefer to keep it the default as our distributions, Google Chrome and others rely upon that for testing.  It's trivial to disable with a local build and we've never had a request top change it.
