### ISSUE TITLE
FEI support

### ISSUE THREAD

**Issue by sat8** [01org/libva#26]
Hi

I need to access the motion vectors generated during H.264 encoding and from the archived messages I see that access to such extra information has been patched https://lists.freedesktop.org/archives/libva/2014-May/002249.html . However, I am unable to see if this is stil supported. Is there a reason for not supporting the side information?

I would like to know if the low level driver and/or other components still support the side information such as motion vectors is still available. I would like to try applying the patch myself but would appreciate to know if there reasons where this patch is not recommended and should be avoided.

Thanks

**Comment by seanvk** [comment]
FEI is not currently supported.  There were some patches merged to a staging branch of Libva, but as of today there is no FEI in the driver backend nor is there any in the front end interface.
