### ISSUE TITLE
Convince me you are using Android.mk, va_android.cpp

### ISSUE THREAD

**Issue by seanvk** [01org/libva#30]
Because we are not testing Android build with it and yet the makefile is still there and we continue to add new files to it with the presumption someone is actually building with it...I'd honestly prefer to see that maintained at the packaging level of an android project.

Begin

**Comment by LoSealL** [comment]
Hi Seanvk, I'm using Android Studio 2.3 (with gradle 3.3) and try to build libva for my android project. The current Android.mk seems doesn't work for me...

For example, some dependencies such as libdrm and libcutils can't be found, and there is no `<surfaceflinger/ISurface.h>` and `<utils/log.h>` any more.
Could you please to help fix them?

**Comment by cwhuang** [comment]
Yes,  the android-x86 and android-ia groups are working on the porting. It would be great if all the effort could be upstreamed.

Indeed the current Android.mk is a little buggy. I'll send you fixes if you agree.

**Comment by xhaihao** [comment]
@cwhuang  If you want,  you're welcome to submit patches to fix the gap.

**Comment by cwhuang** [comment]
As promised, I've sent the pull request:
https://github.com/01org/libva/pull/37

**Comment by xhaihao** [comment]
Closed as @cwhuang fixed the building issue.
