### ISSUE TITLE
For next release switch to a version only tag

### ISSUE THREAD

**Issue by seanvk** [01org/libva#31]
For the next release (1.8.0), I'm going to need us to only use version only in the
tag.  That means if the release is 1.8.0 then that is the actual tag we will apply.
The reason is that on libva we've been appending the name to the tag and as a
result Github doubles the name of the tag.  
So to give you an expample:

Next Release:  1.8.0
Previous Release:  libva-1.7.3

We are simply removing the name from the tag for future releases.  This makes libva consistent with libva-utils and intel-vaapi-driver for release tagging.

Thanks,

Sean

**Comment by xhaihao** [comment]
We have used version only tag for new release.
