### ISSUE TITLE
Fix spelling of roi_rc_qp_delat_support in VAConfigAttribValEncROI

### ISSUE THREAD

**Issue by zzoon** [01org/libva#32]
I think roi_rc_qp_delat_support should be fixed to roi_rc_qp_delta_support.
But I'm not sure how to do this without API-break.

**Comment by seanvk** [comment]
Agree @zzoon

**Comment by RuidongFang** [comment]
There is an error "i965_drv_video.c:1052:41:error:'struct <anonymous>' has no member named 'roi_rc_qp_delat_support' " when I compile "intel-vaapi-driver-1.8.0" in the Skylake with CentOS 7.2. How to solve it?

**Comment by xhaihao** [comment]
@RuidongFang  you should build libva master firstly

**Comment by tuxutku** [comment]
> you should build libva master firstly
What do you mean by you should build master firstly?
i am trying to get libva.so.1 file, is it master provide that file?

**Comment by tuxutku** [comment]
i just made a mistake with installing it directly (sudo make install), its not installed to /usr/local and relinked some binaries

**Comment by xhaihao** [comment]
> What do you mean by you should build master firstly?
> i am trying to get libva.so.1 file, is it master provide that file?

I mean you should build the library from the latest source code. The new library is libva.so.2 when you use the latest master branch

**Comment by tuxutku** [comment]
i allready installed the 1.8 and i have libva.so.1 now, depented program works
i had to revert some relinking some binaries that 1.8 branch did,
