### ISSUE TITLE
Compiler warning in va_enc_h264.h with C++

### ISSUE THREAD

**Issue by scott-d-phillips** [01org/libva#35]
When compiling C++ code which includes va_enc_h264.h, this warning is emitted (marked error below because of -Werror):

```
.../va_enc_h264.h:577:13: error: empty union has size 0 in C, size 1 in C++ [-Werror,-Wextern-c-compat]
            union {
            ^
```

Just deleting the empty `bits` union should fix this without affecting ABI compatibility.

**Comment by xhaihao** [comment]
I think the inner structure should be 
union {
     struct {
     } bits;
     unsigned int value;
  } inter_fields;

otherwise what is the field of value?
