### ISSUE TITLE
Assertion failure when trying to draw big pictures

### ISSUE THREAD

**Issue by l29ah** [01org/libva#51]
Intel(R) Core(TM) i7 CPU L 620 @ 2.00GHz here.
> VO: [vaapi] 10000x10000 yuv420p
> mpv: /var/tmp/paludis/x11-libs-libva-1.8.1/work/libva-1.8.1/va/x11/dri2_util.c:133: union dri_buffer *dri2GetRenderingBuffer(VADriverContextP, struct dri_drawable *): Assertion `buffers' failed.
> /home/l29ah/bin//listen: line 10: 26979 Aborted                 (core dumped) mpv

**Comment by FocusLuo** [comment]
Assigned a P3 priority based on our bug scrub meeting

**Comment by xhaihao** [comment]
The display server doesn't support 10000x10000, https://github.com/01org/libva/pull/56 drops the assertion fault in libva-x11. a similar fix is needed in intel-vaapi-driver.
