### ISSUE TITLE
Possible issue with 1.8.2 tarball hosted on freedesktop.org

### ISSUE THREAD

**Issue by elkrejzi** [01org/libva#52]
Tarball downloaded from https://www.freedesktop.org/software/vaapi/releases/libva/

$ md5sum libva-1.8.2.tar.bz2 
beeaf50f0049692542ad9468d8b7d36f  libva-1.8.2.tar.bz2
$ tar xf libva-1.8.2.tar.bz2 

bzip2: Data integrity error when decompressing.
	Input file = (stdin), output file = (stdout)

It is possible that the compressed file(s) have become corrupted.
You can use the -tvv option to test integrity of such files.

You can use the `bzip2recover' program to attempt to recover
data from undamaged sections of corrupted files.

tar: Child returned status 2
tar: Error is not recoverable: exiting now

**Comment by xhaihao** [comment]
I updated the tarball, please give a try.

We moved libva from freedesktop to github a few months ago, I put a tarball on freedesktop.org in case some user is still unaware of the change,  but it is possible we won't provide the tarball on freedesktop any more, so please check https://github.com/01org/libva/releases for the latest release in the future. 

BTW We only provide SHA1 checksum, please  check the package with sha1sum
