### ISSUE TITLE
Playing videos through LibVA always fails on Wayland

### ISSUE THREAD

**Issue by genodeftest** [01org/libva#53]
This issue was initially reported downstream at https://bugzilla.redhat.com/show_bug.cgi?id=1455101

Description of problem:
When trying to run any libVA based application on wayland, they always fail.

Version-Release number of selected component (if applicable):
totem-3.24.0-1.fc26.x86_64
gstreamer1-vaapi-1.12.0-1.fc26.x86_64
libva-1.8.2-1.fc26.x86_64
libva-intel-driver-1.8.2-1.fc26.x86_64

How reproducible:
always. Ever since I started using wayland (about 2 years ago).

Steps to Reproduce:
1. have the packages installed as noted above
2. run a gnome/wayland session
3. start totem
4. play video file

Actual results:
Green screen, no video output.
Output of totem:

VA error: wayland: failed to identify /dev/dri/card0: Permission denied (errno 13)
libva error: va_getDriverName() failed with unknown libva error,driver_name=(null)
libva error: va_getDriverName() failed with unknown libva error,driver_name=(null)

Expected results:
Work fine

Additional info:
This renders libva completely useless on wayland.

The warning (first line) is printed from drm_handle_device in libva/va/wayland/va_wayland_drm.c.

$ ls -al /dev/dri
drwxr-xr-x.  3 root root       100 23. Mai 06:53 .
drwxr-xr-x. 19 root root      4240 24. Mai 09:54 ..
drwxr-xr-x.  2 root root        80 23. Mai 06:53 by-path
crw-rw----+  1 root video 226,   0 23. Mai 06:53 card0
crw-rw----+  1 root video 226, 128 23. Mai 06:53 renderD128

$ vainfo 
libva info: VA-API version 0.40.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib64/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_40
libva info: va_openDriver() returns 0
vainfo: VA-API version: 0.40 (libva )
vainfo: Driver version: Intel i965 driver for Intel(R) Ironlake Desktop - 1.8.2
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileNone                   :	VAEntrypointVideoProc

Should I add myself to the video group? If yes, shouldn't that be the default for any user?

**Comment by xhaihao** [comment]
devices under  /dev/dri/ are not only used by libva, but also used by other DRI driver, such as opengl, opencl. you should add yourself to the video group if you want to use DRI driver.

**Comment by genodeftest** [comment]
> devices under /dev/dri/ are not only used by libva, but also used by other DRI driver, such as opengl, opencl. you should add yourself to the video group if you want to use DRI driver.

That does not work. still getting the same Error message when starting totem.

**Comment by xhaihao** [comment]
libva is using stat() to get the file status. According to the manual,  the following permission is required to get the file status, could you double check the file path?

"No permissions are required on the file itself, but—in the case of stat(), fstatat(), and lstat()—execute (search) permission is required on all of the directories in pathname that lead to the file."

**Comment by genodeftest** [comment]
> "No permissions are required on the file itself, but—in the case of stat(), fstatat(), and lstat()—execute (search) permission is required on all of the directories in pathname that lead to the file."

That's what I have. See first comment. 

I also tried `# chmod og+rw /dev/dri/card0` and it still does not work. I also made sure there are no AVC denials (SELinux).

Also, a simple program which just calls "open()" on this path works fine. As does this line in python: `open("/dev/dri/card0")`.

**Comment by genodeftest** [comment]
Also, running this under python works fine:

    >>> import os
    >>> os.stat("/dev/dri/card0")
    posix.stat_result(st_mode=8630, st_ino=15852, st_dev=6, st_nlink=1, st_uid=0, st_gid=39, st_size=0, st_atime=1495903682, st_mtime=1495903682, st_ctime=1495908974)

and, what is really weird, when running `$ strace totem`, both `open()` and `stat()` work fine and `stat()` always returns 0:

```
open("/dev/dri/card0", O_RDWR|O_CLOEXEC) = 12
stat("/dev/dri/card0", {st_mode=S_IFCHR|0666, st_rdev=makedev(226, 0), ...}) = 0
stat("/dev/dri/card0", {st_mode=S_IFCHR|0666, st_rdev=makedev(226, 0), ...}) = 0
stat("/dev/dri/card0", {st_mode=S_IFCHR|0666, st_rdev=makedev(226, 0), ...}) = 0
open("/dev/dri/card0", O_RDWR|O_CLOEXEC) = 12
stat("/dev/dri/card0", {st_mode=S_IFCHR|0666, st_rdev=makedev(226, 0), ...}) = 0
stat("/dev/dri/card0", {st_mode=S_IFCHR|0666, st_rdev=makedev(226, 0), ...}) = 0
stat("/dev/dri/card0", {st_mode=S_IFCHR|0666, st_rdev=makedev(226, 0), ...}) = 0
stat("/dev/dri/card0", {st_mode=S_IFCHR|0666, st_rdev=makedev(226, 0), ...}) = 0
```

So it looks like the issue is somewhere else, although I have no clue where.

**Comment by genodeftest** [comment]
Ok, I'm sorry for the noise, the issue is in totem's code: The `stat()` system call fails with `EACCESS` because it is called from totem-video-thumbnailer, which does drop all write privileges before accessing that file.
