### ISSUE TITLE
Inconsistent data type of slice_data_flag in VASliceParameterBufferHEVC

### ISSUE THREAD

**Issue by yakuizhao** [01org/libva#58]
Currently the data type of slice_data_flag in VASliceParameterBufferHEVC is uint16_t while it is uint32_t for other codecs.(VASliceParameterBufferAVC/VP8/VP9). In such case it is not consistent.
In fact as the memory is allocated as aligned, it still allocates four bytes for slice_data_flag. 
So it will be better to use the consistent data type.

**Comment by xhaihao** [comment]
Closed as the patch was merged into v2.0-branch
