### ISSUE TITLE
libva-vdpau-driver-0.7.4/src/sysdeps.h:52:13: implicit declaration of function "vdpau_error_message"

### ISSUE THREAD

**Issue by XVilka** [01org/libva#93]
Sorry, I haven't found libva-vdpau-driver repository in this organization, thus filling the bug here:

/var/tmp/portage/x11-libs/libva-vdpau-driver-0.7.4-r4/work/libva-vdpau-driver-0.7.4/src/sysdeps.h:52:13:
warning: implicit declaration of function "vdpau_error_message" [-Wimplicit-function-declaration]

**Comment by chivakker** [comment]
This is not libva-vdpau-driver repository.
