### ISSUE TITLE
intel_gpu_top shows different in different linux kernel,why?

### ISSUE THREAD

**Issue by waiter89** [01org/libva#97]
I decode the same video using the same program libva and libva-intel-driver,Opensuse ,CPU N3150

kernel  4.3.3

  render busy:  32%: ██████▌                                render space: 30/131072

                          task  percent busy
                           GAM:  41%: ████████▎               vert fetch: 0 (0/sec)
                            CS:  34%: ██████▉                 prim fetch: 0 (0/sec)
                            VF:   7%: █▌                   VS invocations: 0 (0/sec)
                            VS:   7%: █▌                   GS invocations: 0 (0/sec)
                            SF:   7%: █▌                        GS prims: 0 (0/sec)
                            CL:   7%: █▌                   CL invocations: 0 (0/sec)
                          GAFS:   7%: █▌                        CL prims: 0 (0/sec)
                            GS:   7%: █▌                   PS invocations: 0 (0/sec)
                           SOL:   7%: █▌                   PS depth pass: 0 (0/sec)
                            DS:   7%: █▌                  
                           TSG:   0%:                     
                           VFE:   0%:                     
                            RS:   0%:                     
                           SDE:   0%:                     
                           SVG:   0%:                     
                            HS:   0%:                     
                          GAFM:   0%:                     
                            TE:   0%: 

kernel 4.6.3 or above

  render busy:  60%: ████████████                           render space: 46/16384

                          task  percent busy
                           GAM:  68%: █████████████▋          vert fetch: 0 (0/sec)
                            CS:  61%: ████████████▎           prim fetch: 0 (0/sec)
                           SDE:   8%: █▋                   VS invocations: 0 (0/sec)
                            RS:   0%:                      GS invocations: 0 (0/sec)
                            VF:   0%:                           GS prims: 0 (0/sec)
                          GAFM:   0%:                      CL invocations: 0 (0/sec)
                           SOL:   0%:                           CL prims: 0 (0/sec)
                           TSG:   0%:                      PS invocations: 0 (0/sec)
                            VS:   0%:                      PS depth pass: 0 (0/sec)
                           VFE:   0%:                     
                           SVG:   0%:                     
                            SF:   0%:                     
                            CL:   0%:                     
                            GS:   0%:

**Comment by xhaihao** [comment]
Please try the latest stable Linux kernel. Please file a i915 KMD issue if you still experience this issue. I'm very sorry I don't know what was changed in i915 KMD.
